# Homework Module 2 LLM Zoomcamp

Qdrant uses fastembed under the hood to turn text into vectors.

We will now explore this library

Make sure it's installed:
```
pip install fastembed
```

In [17]:
import pandas as pd
import numpy as np

In [1]:
from fastembed import TextEmbedding

## Q1

Embed the query: `'I just discovered the course. Can I join now?'`. Use the `'jinaai/jina-embeddings-v2-small-en'` model.

You should get a numpy array of size 512.

What's the minimal value in this array?

- -0.51
- **-0.11**
- 0
- 0.51



In [4]:
from qdrant_client import QdrantClient, models

In [5]:
# Initialize the client
client = QdrantClient("http://localhost:6333") #connecting to local Qdrant instance

In [2]:
query = 'I just discovered the course. Can I join now?'
print(query)

I just discovered the course. Can I join now?


In [3]:
model_handle = "jinaai/jina-embeddings-v2-small-en"

In [25]:
# Embed the query
model = TextEmbedding(model_handle)
embedded_query = np.array(list(model.embed([query])))[0]

In [26]:
embedded_query.shape

(512,)

In [27]:
embedded_query.min()

np.float64(-0.11726373885183883)

## Cosine similarity

The vectors that our embedding model returns are already normalized: their length is 1.0.

You can check that by using the norm function:
```
import numpy as np
np.linalg.norm(q)
```
Which means that we can simply compute the dot product between two vectors to learn the cosine similarity between them.

For example, if you compute the cosine of the query vector with itself, the result will be 1.0:
```
q.dot(q)
```

In [29]:
q = embedded_query
print(np.linalg.norm(q))
print(q.dot(q))

1.0
1.0000000000000002


## Q2

Now let's embed this document:
```
doc = 'Can I still join the course after the start date?'
```
What's the cosine similarity between the vector for the query and the vector for the document?

- 0.3
- 0.5
- 0.7
- **0.9**

In [30]:
# The document
doc = 'Can I still join the course after the start date?'

In [36]:
# Embed the document
embedded_doc = np.array(list(model.embed([doc])))[0]

In [33]:
d = embedded_doc
print(d.dot(q))
print(q.dot(d))

0.9008528895674548
0.9008528895674548


## Q3

For Q3 and Q4 we will use these documents:

```
documents = [{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
  'section': 'General course-related questions',
  'question': 'Course - Can I follow the course after it finishes?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'You can start by installing and setting up all the dependencies and requirements:\nGoogle cloud account\nGoogle Cloud SDK\nPython 3 (installed with Anaconda)\nTerraform\nGit\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
  'section': 'General course-related questions',
  'question': 'Course - What can I do before the course starts?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Star the repo! Share it with friends if you find it useful ❣️\nCreate a PR if you see you can improve the text or the structure of the repository.',
  'section': 'General course-related questions',
  'question': 'How can we contribute to the course?',
  'course': 'data-engineering-zoomcamp'}]
```

Compute the embeddings for the text field, and compute the cosine between the query vector and all the documents.

What's the document index with the highest similarity? (Indexing starts from 0):

- 0
- **1**
- 2
- 3
- 4
  
_Hint_: if you put all the embeddings of the text field in one matrix V (a single 2-dimensional numpy array), then computing the cosine becomes a matrix multiplication:

```
V.dot(q)
```
If this hint is rather confusing you than helping, feel free to ignore it.

In [34]:
documents = [{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
  'section': 'General course-related questions',
  'question': 'Course - Can I follow the course after it finishes?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'You can start by installing and setting up all the dependencies and requirements:\nGoogle cloud account\nGoogle Cloud SDK\nPython 3 (installed with Anaconda)\nTerraform\nGit\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
  'section': 'General course-related questions',
  'question': 'Course - What can I do before the course starts?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Star the repo! Share it with friends if you find it useful ❣️\nCreate a PR if you see you can improve the text or the structure of the repository.',
  'section': 'General course-related questions',
  'question': 'How can we contribute to the course?',
  'course': 'data-engineering-zoomcamp'}]

In [58]:
all_text = [doc['text'] for doc in documents]
print(all_text)

["Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.", 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.', "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.", 'You can start by installin

In [64]:
embedded_documents = np.array(list(model.embed(all_text)))

embedded_documents

array([[-0.0249525 , -0.0396454 , -0.00437672, ...,  0.06779866,
         0.0377203 , -0.00470724],
       [-0.0594709 , -0.08523984,  0.01292091, ...,  0.09599709,
         0.05420843, -0.00029461],
       [-0.06846454, -0.04079098,  0.04998121, ...,  0.06578071,
         0.02872077, -0.01115215],
       [-0.04640506, -0.02555229,  0.02241224, ...,  0.03410312,
         0.06813592, -0.0064033 ],
       [-0.05394912, -0.04693814,  0.00794725, ...,  0.05402997,
         0.03033385, -0.01254518]], shape=(5, 512))

In [67]:
embedded_documents.dot(q)

array([0.76296847, 0.81823782, 0.80853974, 0.7133079 , 0.73044992])

In [68]:
embedded_documents.dot(q).argmax()

np.int64(1)

## Q4

Now let's calculate a new field, which is a concatenation of question and text:
```
full_text = doc['question'] + ' ' + doc['text']
```
Embed this field and compute the cosine between it and the query vector. What's the highest scoring document?

- **0**
- 1
- 2
- 3
- 4

Is it different from Q3? If yes, why?

In [69]:
full_text = [doc['question'] + ' ' + doc['text'] for doc in documents]
print(full_text)

["Course - Can I still join the course after the start date? Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.", 'Course - Can I follow the course after it finishes? Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.', "Course - When will the course start? The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the

In [74]:
embedded_fulltext = np.array(list(model.embed(full_text)))

embedded_fulltext

array([[-0.03958748, -0.06904069,  0.01146618, ...,  0.09114032,
         0.04739896, -0.01033183],
       [-0.08249755, -0.08627812,  0.00593604, ...,  0.10836487,
         0.05654416,  0.00051011],
       [-0.07798266, -0.05428376,  0.05052968, ...,  0.07455595,
         0.04321019, -0.01098255],
       [-0.0719691 , -0.05147855,  0.02265294, ...,  0.04538724,
         0.09451547, -0.00157571],
       [-0.08384529, -0.05699563,  0.00955793, ...,  0.04386464,
         0.034007  , -0.01080237]], shape=(5, 512))

In [75]:
embedded_fulltext.dot(q)

array([0.85145432, 0.84365942, 0.8408287 , 0.7755158 , 0.80860078])

In [76]:
embedded_fulltext.dot(q).argmax()

np.int64(0)

The 0th document after incorporating the question field is more similar to the query because a lot more keywords from the query is shows on the question field. 

## Q5. Selecting the embedding model
Now let's select a smaller embedding model. What's the smallest dimensionality for models in fastembed?

- 128
- 256
- **384**
- 512

In [81]:
smallest_dimensionality = np.min([model['dim'] for model in TextEmbedding.list_supported_models()])
smallest_dimensionality

np.int64(384)

In [87]:
TextEmbedding.list_supported_models()[3]

{'model': 'BAAI/bge-small-en',
 'sources': {'hf': 'Qdrant/bge-small-en',
  'url': 'https://storage.googleapis.com/qdrant-fastembed/BAAI-bge-small-en.tar.gz',
  '_deprecated_tar_struct': True},
 'model_file': 'model_optimized.onnx',
 'description': 'Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2023 year.',
 'license': 'mit',
 'size_in_GB': 0.13,
 'additional_files': [],
 'dim': 384,
 'tasks': {}}

One of these models is `BAAI/bge-small-en`. Let's use it.

## Q6. Indexing with qdrant (2 points)
For the last question, we will use more documents.

We will select only FAQ records from our ml zoomcamp:

```
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()


documents = []

for course in documents_raw:
    course_name = course['course']
    if course_name != 'machine-learning-zoomcamp':
        continue

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)
```
Add them to qdrant using the model form Q5.

When adding the data, use both question and answer fields:

```
text = doc['question'] + ' ' + doc['text']
```

After the data is inserted, use the question from Q1 for querying the collection.

What's the highest score in the results? (The score for the first returned record):

- 0.97
- **0.87**
- 0.77
- 0.67

In [88]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()


documents = []

for course in documents_raw:
    course_name = course['course']
    if course_name != 'machine-learning-zoomcamp':
        continue

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [90]:
documents[0]

{'text': 'Machine Learning Zoomcamp FAQ\nThe purpose of this document is to capture frequently asked technical questions.\nWe did this for our data engineering course and it worked quite well. Check this document for inspiration on how to structure your questions and answers:\nData Engineering Zoomcamp FAQ\nIn the course GitHub repository there’s a link. Here it is: https://airtable.com/shryxwLd0COOEaqXo\nwork',
 'section': 'General course-related questions',
 'question': 'How do I sign up?',
 'course': 'machine-learning-zoomcamp'}

In [94]:
# Create a collection

model_handle = "BAAI/bge-small-en"
collection_name = "HW2"
EMBEDDING_DIMENSIONALITY = smallest_dimensionality

In [ ]:
# Create the collection with specified vector parameters
# Run only ONCE

# client.create_collection(
#     collection_name=collection_name,
#     vectors_config=models.VectorParams(
#         size=EMBEDDING_DIMENSIONALITY,  # Dimensionality of the vectors
#         distance=models.Distance.COSINE  # Distance metric for similarity search
#     )
# )

In [95]:
points = []
id = 0

for course in documents_raw:
    for doc in course['documents']:

        point = models.PointStruct(
            id=id,
            vector=models.Document(text=doc['question'] + ' ' + doc['text'], model=model_handle), #embed text locally with "jinaai/jina-embeddings-v2-small-en" from FastEmbed
            payload={
                "text": doc['text'],
                "section": doc['section'],
                "course": course['course']
            } #save all needed metadata fields
        )
        points.append(point)

        id += 1

In [97]:
client.upsert(
    collection_name=collection_name,
    points=points
)

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

model_optimized.onnx:   0%|          | 0.00/133M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/701 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

In [98]:
def search(query, limit=1):

    results = client.query_points(
        collection_name=collection_name,
        query=models.Document( #embed the query text locally with "jinaai/jina-embeddings-v2-small-en"
            text=query,
            model=model_handle 
        ),
        limit=limit, # top closest matches
        with_payload=True #to get metadata in the results
    )

    return results

In [99]:
query = 'I just discovered the course. Can I join now?'
result = search(query)

result

QueryResponse(points=[ScoredPoint(id=449, version=1, score=0.8703172, payload={'text': 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.', 'section': 'General course-related questions', 'course': 'machine-learning-zoomcamp'}, vector=None, shard_key=None, order_value=None)])